### ISSUE TITLE
EDM-G IMX8MP SOM

### ISSUE THREAD

**Issue by LeoChang88** [TechNexion/tn-imx-yocto-manifest#32]
Hello,

Is this repository ready for REV.B image building?

thanks.

**Comment by richard-hu** [comment]
Hi, Leo:

I update recipes in TN BSP meta layer to point to latest kernel and u-boot.
https://github.com/TechNexion/meta-tn-imx-bsp/commit/29c9766b3e484ecc5877085200bfde4b3f621467
https://github.com/TechNexion/meta-tn-imx-bsp/commit/d0d67e9dab2ed426ae8316bdce92b8c9f4ffb72a

Could you give it a try?
Please use `-next` branch instead of `-stable`.

https://github.com/TechNexion/tn-imx-yocto-manifest/tree/hardknott_5.10.y-next

$: repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-next -m imx-5.10.72-2.2.0.xml
$: repo sync -j8

**Comment by VecowSoftware** [comment]
Hi @richard-hu ,
I have finished the image building process, and it can boot with EDM-G-WB carrier board REV B,
but we can not boot it with our customized carrier board,
could you help to check this?
[customized.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8629596/customized.txt)
[edm-g-wb.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8629597/edm-g-wb.txt)

**Comment by LeoChang88** [comment]
Hi @richard-hu ,

I have finished the image building process, and it can boot with EDM-G-WB carrier board REV B,
but we can not boot it with our customized carrier board,
could you help to check this?
[customized.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8629596/customized.txt)
[edm-g-wb.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8629597/edm-g-wb.txt)

**Comment by richard-hu** [comment]
Hi, Leo:

有看到您提供的log。
看起來是u-boot沒load到kernel image，
可以先在u-boot prompt，
用fatload mmc指令試試看能不能手動load到kernel image.

BR,

Richard

**Comment by LeoChang88** [comment]
Hi @richard-hu ,

Micro SD部分的電路修改後已經可以開機了，謝謝。

**Comment by ray-chang** [comment]
The issue has been solved and the root cause was on the customer's board.
