### ISSUE TITLE
eth0 didn't work

### ISSUE THREAD

**Issue by kikiyami** [TechNexion/tn-imx-yocto-manifest#4]
My hardware is an imx6 solo.
Before, I used the version https://github.com/TechNexion/edm-yocto-bsp works fine.
But the GStreamer version is too low, so I change this version.
But seems eth0 didn't work
I try to create a setup file to /lib/systemd/network or
 refer to the URL https://www.yoctoproject.org/pipermail/yocto/2014-December/022730.html
but it still can't work.

Any suggestion?
Thanks

**Comment by richard-hu** [comment]
@kikiyami 

Thanks for your feedback.
The ethernet problem was fixed in `-next` branch.
https://github.com/TechNexion/linux-tn-imx/commit/7ae5a77a22f3e098093a42bfb4edc656b09efcb3

We will merge the changes to `stable` branch after our test team completes the test for 2020Q2 release.  

Could you change to use `next` branch of tn-imx-yocto-manifest?
It refers to `next` branch of `meta-tn-imx-bsp` 
(the meta layer refers to `next` branch of linux kernel)
https://github.com/TechNexion/tn-imx-yocto-manifest/tree/sumo_4.14.y_GA-next

BR,

Richard
