### ISSUE TITLE
Support for Yocto releases more recent than Sumo

### ISSUE THREAD

**Issue by arrow53** [TechNexion/tn-imx-yocto-manifest#7]
Is there support for any later Yocto releases, such as zeus? Even if this has just been experimental I'd be curious.

**Comment by richard-hu** [comment]
@arrow53 

I apologize for the late reply.
(Because we are working on Linux 5.4.24 kernel for Yocto Zeus)

We already make some progress on PICO-IMX8MM on Yocto Zeus.

We will put it on github in the near future.
TechNexion i.mx8 products will be upgraded first. 
(PICO-IMX8MM, PICO-IMX8MQ)
Then, i.mx6 and i.mx7 will be upgraded later.

Don't worry. The development of Yocto Zeus is on-going.

BR,

Richard

**Comment by arrow53** [comment]
awesome. We are using xore but great to hear updates coming. dunfell is an lts so that would be a nice one at some point.

**Comment by geoffrey-vl** [comment]
Hi @richard-hu , do you think you'll be supporting the Yocto LTS release (Dunfell) in the future?

**Comment by richard-hu** [comment]
@geoffrey-vl 

Sorry for the late reply.
In order to support latest i.mx8 SOC(i.mx8M Plus), we choose to use BSP from NXP official release instead of community. 
But NXP doesn't have plan to support Yocto Dunfell for i.mx family.
https://community.nxp.com/t5/i-MX-Processors/Is-Yocto-dunfell-branch-supported-by-imx-manifest/m-p/1080021
Currently, NXP Yocto stays on Yocto Zeus for linux 5.4.x BSP.

We know Yocto Dunfell is the first LTS version for Yocto.
Currently, we just release Yocto Zeus for some TechNexion products.
We are evaluating to use Zeus meta layer from NXP but replace the other meta layers with Dunfell.
It might take more effort to test if everything still works fine.

BR,

Richard
